Remove pre-downloaded deps. Remove .vim/ a bit of tidying.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -18,17 +18,31 @@ dotfiles=(
     bashrc
     gitconfig
 	vimrc
-	vim
 )
 for f in "${dotfiles[@]}"; do
 	[[ -d ~/.$f && ! -L ~/.$f ]] && rm -r ~/."$f"
 	symlink "$PWD/$f" ~/."$f"
 done
 
+# Create some files for use later
+touch ~/.local.vimrc
+mkdir ~/.vim
+
+# Check for curl
+if ! command -v curl &> /dev/null; then
+    echo "Error: curl is not installed. Cannot download vim-plug" >&2
+    exit 1
+fi
+
+# Download and install the latest vim-plug
+curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
+    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
+
+# If we're interactive, then run the PlugInstall
 if [[ -t 1 ]]; then
 	vim '+PlugInstall --sync' +qa
 else
-	printf "may need to run:\n\tvim +'PlugInstall --sync' +qa\n"
+	printf "May need to run:\n\tvim +'PlugInstall --sync' +qa\n"
 fi
 
 true
